export type AgentToolMode = "cli" | "editor" | "framework" | "service" | "hosted";
export type InstallerKind = "npm" | "python" | "manual" | "none";

export interface AgentToolInstaller {
  kind: InstallerKind;
  packageName?: string;
  executable?: string;
  note?: string;
}

export interface AgentToolDefinition {
  id: string;
  name: string;
  publisher: string;
  mode: AgentToolMode;
  description: string;
  officialUrl: string;
  docsUrl?: string;
  repositoryUrl?: string;
  executable?: string;
  iconSlug: string;
  capabilities: string[];
  installer: AgentToolInstaller;
}

const github = (repo: string): string => `https://github.com/${repo}`;

const cli = (tool: Omit<AgentToolDefinition, "mode" | "installer"> & { packageName?: string; installerKind?: "npm" | "python" | "manual" }): AgentToolDefinition => {
  const { packageName, installerKind, ...definition } = tool;
  const installer: AgentToolInstaller = installerKind && packageName
    ? { kind: installerKind, packageName, ...(definition.executable ? { executable: definition.executable } : {}) }
    : { kind: installerKind ?? "manual", ...(definition.executable ? { executable: definition.executable } : {}), note: "Follow the official installation guide." };
  return { ...definition, mode: "cli", installer };
};

const catalog: AgentToolDefinition[] = [
  cli({ id: "hermes", name: "Hermes Agent", publisher: "Nous Research", description: "Local terminal agent with tools, memory, skills, and delegation.", officialUrl: "https://hermes-agent.nousresearch.com/", docsUrl: "https://hermes-agent.nousresearch.com/docs/getting-started/quickstart", repositoryUrl: github("NousResearch/hermes-agent"), executable: "hermes", iconSlug: "hermes", capabilities: ["chat", "terminal", "memory", "mcp"] }),
  cli({ id: "claude-code", name: "Claude Code", publisher: "Anthropic", description: "Anthropic coding agent for terminal workflows.", officialUrl: "https://docs.anthropic.com/en/docs/claude-code/overview", repositoryUrl: "https://github.com/anthropics/claude-code", executable: "claude", iconSlug: "claude", capabilities: ["chat", "terminal", "coding"], installerKind: "npm", packageName: "@anthropic-ai/claude-code" }),
  cli({ id: "codex", name: "Codex CLI", publisher: "OpenAI", description: "OpenAI local coding agent for reading, editing, and running code.", officialUrl: "https://developers.openai.com/codex", docsUrl: "https://github.com/openai/codex", repositoryUrl: github("openai/codex"), executable: "codex", iconSlug: "openai", capabilities: ["chat", "terminal", "coding"], installerKind: "npm", packageName: "@openai/codex" }),
  cli({ id: "openclaw", name: "OpenClaw", publisher: "OpenClaw", description: "Open agent runtime entry in the local catalog.", officialUrl: "https://github.com/openclaw/openclaw", repositoryUrl: github("openclaw/openclaw"), executable: "openclaw", iconSlug: "openclaw", capabilities: ["chat", "terminal"] }),
  cli({ id: "deepcode", name: "DeepCode", publisher: "DeepCode", description: "Code intelligence agent entry with an official source link.", officialUrl: "https://github.com/snyk/DeepCode", repositoryUrl: github("snyk/DeepCode"), executable: "deepcode", iconSlug: "deepcode", capabilities: ["coding"] }),
  cli({ id: "aider", name: "Aider", publisher: "Aider AI", description: "AI pair programming in your terminal.", officialUrl: "https://aider.chat/", docsUrl: "https://aider.chat/docs/install.html", repositoryUrl: github("Aider-AI/aider"), executable: "aider", iconSlug: "aider", capabilities: ["chat", "terminal", "coding"], installerKind: "python", packageName: "aider-chat" }),
  cli({ id: "openhands", name: "OpenHands", publisher: "OpenHands", description: "Self-hosted developer control center and agent server.", officialUrl: "https://openhands.dev/", docsUrl: "https://docs.openhands.dev/", repositoryUrl: github("OpenHands/OpenHands"), executable: "openhands", iconSlug: "openhands", capabilities: ["chat", "coding", "automation"] }),
  cli({ id: "devin", name: "Devin", publisher: "Cognition", description: "Hosted AI software engineer.", officialUrl: "https://devin.ai/", executable: "devin", iconSlug: "devin", capabilities: ["hosted-chat", "coding"] }),
  cli({ id: "cline", name: "Cline", publisher: "Cline", description: "Open source coding agent for terminal and editors.", officialUrl: "https://cline.bot/", docsUrl: "https://docs.cline.bot/", repositoryUrl: github("cline/cline"), executable: "cline", iconSlug: "cline", capabilities: ["chat", "terminal", "coding", "mcp"], installerKind: "npm", packageName: "cline" }),
  cli({ id: "continue", name: "Continue", publisher: "Continue", description: "Open source coding agent with CLI and editor integrations.", officialUrl: "https://www.continue.dev/", repositoryUrl: github("continuedev/continue"), executable: "cn", iconSlug: "continue", capabilities: ["chat", "coding", "editor"] }),
  cli({ id: "goose", name: "Goose", publisher: "Block / AAIF", description: "Native open source agent for code, workflows, and automation.", officialUrl: "https://block.github.io/goose/", docsUrl: "https://goose-docs.ai/docs/getting-started/installation", repositoryUrl: github("aaif-goose/goose"), executable: "goose", iconSlug: "goose", capabilities: ["chat", "terminal", "mcp"], installerKind: "manual" }),
  cli({ id: "gemini-cli", name: "Gemini CLI", publisher: "Google", description: "Google Gemini agent for terminal workflows.", officialUrl: "https://geminicli.com/", repositoryUrl: github("google-gemini/gemini-cli"), executable: "gemini", iconSlug: "google", capabilities: ["chat", "terminal", "coding"], installerKind: "npm", packageName: "@google/gemini-cli" }),
  cli({ id: "qwen-code", name: "Qwen Code", publisher: "Alibaba Qwen", description: "Open source terminal coding agent optimized for Qwen models.", officialUrl: "https://qwen.ai/qwencode", repositoryUrl: github("QwenLM/qwen-code"), executable: "qwen", iconSlug: "qwen", capabilities: ["chat", "terminal", "coding"] }),
  cli({ id: "swe-agent", name: "SWE-agent", publisher: "SWE-agent", description: "Research software engineering agent for issue-to-patch workflows.", officialUrl: "https://swe-agent.com/", repositoryUrl: github("SWE-agent/SWE-agent"), executable: "sweagent", iconSlug: "sweagent", capabilities: ["coding", "automation"] }),
  cli({ id: "opencode", name: "OpenCode", publisher: "OpenCode", description: "Open source coding agent for terminal workflows.", officialUrl: "https://opencode.ai/", repositoryUrl: github("anomalyco/opencode"), executable: "opencode", iconSlug: "opencode", capabilities: ["chat", "terminal", "coding"] }),
  cli({ id: "plandex", name: "Plandex", publisher: "Plandex", description: "Terminal-based AI coding engine for large tasks.", officialUrl: "https://plandex.ai/", repositoryUrl: github("plandex-ai/plandex"), executable: "plandex", iconSlug: "plandex", capabilities: ["chat", "terminal", "coding"] }),
  cli({ id: "gpt-engineer", name: "GPT Engineer", publisher: "GPT Engineer", description: "Code generation and project-building agent.", officialUrl: "https://gptengineer.app/", repositoryUrl: github("gpt-engineer-org/gpt-engineer"), executable: "gpt-engineer", iconSlug: "gptengineer", capabilities: ["coding"] }),
  cli({ id: "gpt-pilot", name: "GPT Pilot", publisher: "Pythagora", description: "Developer agent for building applications with AI.", officialUrl: "https://github.com/Pythagora-io/gpt-pilot", repositoryUrl: github("Pythagora-io/gpt-pilot"), executable: "gpt-pilot", iconSlug: "gptpilot", capabilities: ["coding"] }),
  cli({ id: "mentat", name: "Mentat", publisher: "Mentat", description: "Command-line coding assistant.", officialUrl: "https://mentat.ai/", repositoryUrl: github("mentat-ai/mentat"), executable: "mentat", iconSlug: "mentat", capabilities: ["chat", "coding"] }),
  cli({ id: "devika", name: "Devika", publisher: "Stition AI", description: "Open source AI software engineer.", officialUrl: "https://github.com/stitionai/devika", repositoryUrl: github("stitionai/devika"), executable: "devika", iconSlug: "devika", capabilities: ["coding", "automation"] }),
  cli({ id: "open-interpreter", name: "Open Interpreter", publisher: "Open Interpreter", description: "Natural-language interface for running code locally.", officialUrl: "https://openinterpreter.com/", repositoryUrl: github("OpenInterpreter/open-interpreter"), executable: "interpreter", iconSlug: "openinterpreter", capabilities: ["chat", "terminal", "computer"], installerKind: "python", packageName: "open-interpreter" }),
  cli({ id: "crush", name: "Crush", publisher: "Charm", description: "Terminal coding agent from Charm.", officialUrl: "https://github.com/charmbracelet/crush", repositoryUrl: github("charmbracelet/crush"), executable: "crush", iconSlug: "crush", capabilities: ["chat", "terminal", "coding"] }),
  cli({ id: "amp", name: "Amp", publisher: "Sourcegraph", description: "Agentic coding tool for terminal workflows.", officialUrl: "https://ampcode.com/", executable: "amp", iconSlug: "amp", capabilities: ["chat", "coding"] }),
  cli({ id: "zed", name: "Zed", publisher: "Zed Industries", description: "High-performance editor with agent capabilities.", officialUrl: "https://zed.dev/", repositoryUrl: github("zed-industries/zed"), executable: "zed", iconSlug: "zed", capabilities: ["editor", "coding"] }),
  cli({ id: "roo-code", name: "Roo Code", publisher: "Roo Code", description: "Open source coding agent for editor workflows.", officialUrl: "https://roocode.com/", repositoryUrl: github("RooCodeInc/Roo-Code"), executable: "roo", iconSlug: "roocode", capabilities: ["editor", "coding"] }),
  cli({ id: "agent-zero", name: "Agent Zero", publisher: "Agent Zero", description: "General-purpose local agent framework.", officialUrl: "https://github.com/frdel/agent-zero", repositoryUrl: github("frdel/agent-zero"), executable: "agent-zero", iconSlug: "agentzero", capabilities: ["chat", "automation"] }),
  cli({ id: "freebuff", name: "Freebuff", publisher: "Freebuff", description: "Agent tool catalog entry with official source metadata.", officialUrl: "https://github.com/freebuff/freebuff", repositoryUrl: github("freebuff/freebuff"), executable: "freebuff", iconSlug: "freebuff", capabilities: ["chat"] }),
  { id: "bolt-diy", name: "Bolt.diy", publisher: "StackBlitz", mode: "service", description: "Self-hosted full-stack application builder.", officialUrl: "https://github.com/stackblitz-labs/bolt.diy", repositoryUrl: github("stackblitz-labs/bolt.diy"), iconSlug: "bolt", capabilities: ["service", "coding"], installer: { kind: "manual", note: "Run the official self-hosted application instructions." } },
  { id: "open-lovable", name: "Open-Lovable", publisher: "Open-Lovable", mode: "service", description: "Open source application generation workspace.", officialUrl: "https://github.com/mendableai/open-lovable", repositoryUrl: github("mendableai/open-lovable"), iconSlug: "openlovable", capabilities: ["service", "coding"], installer: { kind: "manual" } },
  { id: "autogpt", name: "AutoGPT", publisher: "Significant Gravitas", mode: "service", description: "Self-hosted autonomous agent platform.", officialUrl: "https://agpt.co/", repositoryUrl: github("Significant-Gravitas/AutoGPT"), iconSlug: "autogpt", capabilities: ["service", "automation"], installer: { kind: "manual" } },
  { id: "crewai", name: "CrewAI", publisher: "CrewAI", mode: "framework", description: "Python framework for orchestrating role-playing multi-agent workflows.", officialUrl: "https://www.crewai.com/", repositoryUrl: github("crewAIInc/crewAI"), iconSlug: "crewai", capabilities: ["framework", "orchestration"], installer: { kind: "python", packageName: "crewai" } },
  { id: "metagpt", name: "MetaGPT", publisher: "Foundation Agents", mode: "framework", description: "Multi-agent framework for software company workflows.", officialUrl: "https://deepwisdom.ai/", repositoryUrl: github("FoundationAgents/MetaGPT"), iconSlug: "metagpt", capabilities: ["framework", "orchestration"], installer: { kind: "python", packageName: "metagpt" } },
  { id: "chatdev", name: "ChatDev", publisher: "OpenBMB", mode: "framework", description: "Multi-agent software development framework.", officialUrl: "https://github.com/OpenBMB/ChatDev", repositoryUrl: github("OpenBMB/ChatDev"), iconSlug: "chatdev", capabilities: ["framework", "orchestration"], installer: { kind: "manual" } },
  { id: "autogen", name: "Microsoft AutoGen", publisher: "Microsoft", mode: "framework", description: "Framework for multi-agent applications.", officialUrl: "https://microsoft.github.io/autogen/", repositoryUrl: github("microsoft/autogen"), iconSlug: "microsoft", capabilities: ["framework", "orchestration"], installer: { kind: "python", packageName: "autogen-agentchat" } },
  { id: "langgraph", name: "LangGraph", publisher: "LangChain", mode: "framework", description: "Graph-based agent orchestration runtime.", officialUrl: "https://langchain-ai.github.io/langgraph/", repositoryUrl: github("langchain-ai/langgraph"), iconSlug: "langchain", capabilities: ["framework", "orchestration"], installer: { kind: "python", packageName: "langgraph" } },
  { id: "openai-swarm", name: "OpenAI Swarm", publisher: "OpenAI", mode: "framework", description: "Educational multi-agent orchestration framework.", officialUrl: "https://github.com/openai/swarm", repositoryUrl: github("openai/swarm"), iconSlug: "openai", capabilities: ["framework", "orchestration"], installer: { kind: "python", packageName: "swarm" } },
  { id: "camel", name: "CAMEL", publisher: "CAMEL-AI", mode: "framework", description: "Communicative agents for mind exploration of large scale systems.", officialUrl: "https://www.camel-ai.org/", repositoryUrl: github("camel-ai/camel"), iconSlug: "camel", capabilities: ["framework", "research"], installer: { kind: "python", packageName: "camel-ai" } },
  { id: "taskingai", name: "TaskingAI", publisher: "TaskingAI", mode: "service", description: "Self-hosted platform for building and operating LLM agents.", officialUrl: "https://www.tasking.ai/", repositoryUrl: github("TaskingAI/TaskingAI"), iconSlug: "taskingai", capabilities: ["service", "orchestration"], installer: { kind: "manual" } },
  { id: "dify", name: "Dify", publisher: "LangGenius", mode: "service", description: "Open source platform for LLM apps and agent workflows.", officialUrl: "https://dify.ai/", repositoryUrl: github("langgenius/dify"), iconSlug: "dify", capabilities: ["service", "orchestration"], installer: { kind: "manual" } },
  { id: "flowise", name: "Flowise", publisher: "FlowiseAI", mode: "service", description: "Visual builder for AI agents and LLM workflows.", officialUrl: "https://flowiseai.com/", repositoryUrl: github("FlowiseAI/Flowise"), iconSlug: "flowise", capabilities: ["service", "orchestration"], installer: { kind: "npm", packageName: "flowise" } },
  { id: "beeai", name: "BeeAI Framework", publisher: "IBM", mode: "framework", description: "Framework for production-ready AI agents.", officialUrl: "https://framework.beeai.dev/", repositoryUrl: github("i-am-bee/beeai-framework"), iconSlug: "beeai", capabilities: ["framework", "orchestration"], installer: { kind: "python", packageName: "beeai-framework" } },
  { id: "llamaindex", name: "LlamaIndex", publisher: "LlamaIndex", mode: "framework", description: "Framework for context-augmented LLM applications and agents.", officialUrl: "https://www.llamaindex.ai/", repositoryUrl: github("run-llama/llama_index"), iconSlug: "llamaindex", capabilities: ["framework", "retrieval"], installer: { kind: "python", packageName: "llama-index" } },
  { id: "haystack", name: "Haystack", publisher: "deepset", mode: "framework", description: "Framework for production-ready AI orchestration and retrieval.", officialUrl: "https://haystack.deepset.ai/", repositoryUrl: github("deepset-ai/haystack"), iconSlug: "haystack", capabilities: ["framework", "retrieval"], installer: { kind: "python", packageName: "haystack-ai" } },
  { id: "semantic-kernel", name: "Semantic Kernel", publisher: "Microsoft", mode: "framework", description: "Microsoft SDK for integrating AI agents into applications.", officialUrl: "https://learn.microsoft.com/semantic-kernel/", repositoryUrl: github("microsoft/semantic-kernel"), iconSlug: "microsoft", capabilities: ["framework", "orchestration"], installer: { kind: "python", packageName: "semantic-kernel" } },
  { id: "langchain", name: "LangChain", publisher: "LangChain", mode: "framework", description: "Framework for building context-aware reasoning applications.", officialUrl: "https://www.langchain.com/", repositoryUrl: github("langchain-ai/langchain"), iconSlug: "langchain", capabilities: ["framework", "retrieval"], installer: { kind: "python", packageName: "langchain" } },
  { id: "openclaw-framework", name: "OpenClaw Framework", publisher: "OpenClaw", mode: "framework", description: "Framework entry for OpenClaw ecosystem integrations.", officialUrl: "https://github.com/openclaw/openclaw", repositoryUrl: github("openclaw/openclaw"), iconSlug: "openclaw", capabilities: ["framework"], installer: { kind: "manual" } },
  { id: "babyagi", name: "BabyAGI", publisher: "Yoheinakajima", mode: "framework", description: "Autonomous task-management agent experiment.", officialUrl: "https://github.com/yoheinakajima/babyagi", repositoryUrl: github("yoheinakajima/babyagi"), iconSlug: "babyagi", capabilities: ["framework", "automation"], installer: { kind: "manual" } },
  { id: "agentgpt", name: "AgentGPT", publisher: "reworkd", mode: "service", description: "Browser-based autonomous agent application.", officialUrl: "https://agentgpt.reworkd.ai/", repositoryUrl: github("reworkd/AgentGPT"), iconSlug: "agentgpt", capabilities: ["service", "automation"], installer: { kind: "manual" } },
  { id: "superagi", name: "SuperAGI", publisher: "TransformerOptimus", mode: "framework", description: "Open source autonomous AI agent framework.", officialUrl: "https://github.com/TransformerOptimus/SuperAGI", repositoryUrl: github("TransformerOptimus/SuperAGI"), iconSlug: "superagi", capabilities: ["framework", "automation"], installer: { kind: "manual" } },
  { id: "xagent", name: "XAgent", publisher: "OpenBMB", mode: "framework", description: "Autonomous LLM agent framework.", officialUrl: "https://github.com/OpenBMB/XAgent", repositoryUrl: github("OpenBMB/XAgent"), iconSlug: "xagent", capabilities: ["framework", "automation"], installer: { kind: "manual" } },
];

export const agentToolCatalog = catalog;
export const agentToolMap = new Map(catalog.map((tool) => [tool.id, tool]));
export function getAgentTool(id: string): AgentToolDefinition | undefined { return agentToolMap.get(id); }
